FROM node:22-alpine3.20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --silent --no-audit --ignore-scripts

COPY . .
RUN npm run build

FROM nginx:1.28.0-alpine-slim

RUN rm -rf /etc/nginx/conf.d/default.conf && \
    apk --no-cache upgrade && \
    rm -rf /var/cache/apk/*

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 750 /usr/share/nginx/html && \
    find /usr/share/nginx/html -type f -exec chmod 640 {} \;

USER nginx

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]