FROM node:22-alpine3.20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --silent --no-audit --ignore-scripts --omit=dev

COPY . .

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

RUN npm run build

FROM nginx:1.28.0-alpine-slim

RUN rm -rf /etc/nginx/conf.d/default.conf && \
    apk --no-cache upgrade && \
    rm -rf /var/cache/apk/*

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx/mime.types /etc/nginx/mime.types

RUN chown -R nginx:nginx /usr/share/nginx/html && \
    chmod -R 755 /usr/share/nginx/html && \
    find /usr/share/nginx/html -type f -exec chmod 644 {} \; && \
    chmod 644 /etc/nginx/conf.d/default.conf

HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl -f http://localhost:8080 || exit 1

USER nginx

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]