FROM node:22-alpine3.20

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm ci --silent --no-audit --ignore-scripts --omit=dev

COPY . .

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:3000 || exit 1

CMD ["npm", "start"]